name = "potluck-feast-planner"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = ""

[[rules]]
type = "Text"
globs = ["**/*.txt"]
Fallthrough = true

[[rules]]
type = "CSS"
globs = ["**/*.css"]

[[rules]]
type = "JavascriptModules"
globs = ["**/*.js", "**/*.mjs", "**/*.cjs"]

[[rules]]
type = "ESModules"
globs = ["**/*.js", "**/*.mjs"]